source 'https://rubygems.org'
ruby '2.3.0'

#Core Gems
gem 'rails', '4.2.3'
gem 'sqlite3'
gem 'lograge'

#Front Ends Tools
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'bootstrap-sass', '~> 3.3.5'
gem 'simple_form'
gem 'font-awesome-sass', '~> 4.4.0'

#Other
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'turbolinks'

group :development, :test do
  gem 'byebug'
  gem 'pry-rails'
  gem 'binding_of_caller'
  gem 'better_errors'
  gem 'annotate'
  gem 'spring'
end
